# Create a secret from a file
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=  # admin in base64 format    echo -n 'admin' | base64
  password: MWYyZDFlMmU2N2Rm  # 1f2d1e2e72df  echo -n '1f2d1e2e72df' | base64
