FROM jenkins/jenkins:2.426.1-lts-jdk17
USER root
# Install Docker client cli
RUN apt-get update && \
    apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    apt-key fingerprint 0EBFCD88 && \
    add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/debian \
    $(lsb_release -cs) \
    stable" && \
    apt-get update && \
    apt-get -y install docker-ce-cli
# create docker group
RUN groupadd -g 1001 docker
# add jenkins user to docker group
RUN usermod -aG docker jenkins
USER jenkins
